### ISSUE TITLE
Annotation alignment could be improved

### ISSUE THREAD

**Issue by minad** [JonWaltman/pcmpl-args.el#20]
For long arguments/descriptions sometimes the alignment of the annotations gets jagged. I observe this with my Corfu completion UI, not sure if other UIs are affected too.

**Comment by LemonBreezes** [comment]
> For long arguments/descriptions sometimes the alignment of the annotations gets jagged. I observe this with my Corfu completion UI, not sure if other UIs are affected too.

For Company, no annotations are shown because Company ignores the `annotation-function` of the `completion-table`.

**Comment by minad** [comment]
> For Company, no annotations are shown because Company ignores the annotation-function of the completion-table.

Right, I forget this when I created the issue. This is a bug in Company and should be fixed in `company-capf--annotation`. See https://github.com/company-mode/company-mode/blob/c25f1fbc3850e36e6521b77fa1641d5583365d8b/company-capf.el#L167-L176

**Comment by LemonBreezes** [comment]
> > For Company, no annotations are shown because Company ignores the annotation-function of the completion-table.
> 
> Right, I forget this when I created the issue. This is a bug in Company and should be fixed in `company-capf--annotation`. See [company-mode/company-mode@`c25f1fb`/company-capf.el#L167-L176](https://github.com/company-mode/company-mode/blob/c25f1fbc3850e36e6521b77fa1641d5583365d8b/company-capf.el#L167-L176)

I have written a patch for `company-capf` and have submitted it in this [Company Mode's #1305](https://github.com/company-mode/company-mode/issues/1305).

**Comment by LemonBreezes** [comment]
Hello @minad. So I've found the cause of this issue. The issue is in `pcmpl-args-make-completion-annotator`, and in particular in the way that `pcmpl-args-guess-display-width` determines the display width. Is there a way to determine the width of the completion frame? My intuition is that this would have to be implemented for each completion front-end individually to work. We use this so that we can have `ls --color[=WHEN] ...` even though the `--color` part is the candidate and `[=WHEN]` is part of the annotation.

I am not sure if there is a better way to do this.
