### ISSUE TITLE
Regression: Long argument expansion is broken in Eshell

### ISSUE THREAD

**Issue by minad** [JonWaltman/pcmpl-args.el#28]
@LemonBreezes' recent commit e51aae79a7aeaac677f7bd0c0b3c18c7cdea5d91 unfortunately leads to a regression. I suggest to revert it until a more targeted solution is found. Try `ls --color= TAB` with and without e51aae79a7aeaac677f7bd0c0b3c18c7cdea5d91. The expected completion candidates are the option values `no`, `yes`, etc. With the try-first hook file completions are offered instead.

**Comment by minad** [comment]
The problem seems to be `eshell-complete-variable-assignment`. If I execute this in eshell it works:

~~~ elisp
(setq pcomplete-try-first-hook
      '(eshell-complete-host-reference
        eshell-complete-history-reference
        eshell-complete-user-reference
        ;;eshell-complete-variable-assignment
        eshell-complete-variable-reference
        eshell-complete-lisp-symbols
        t))
~~~

I am not sure about the best fix.

**Comment by CeleritasCelery** [comment]
I am going to revert this until it can be looked into more. On another note, I wonder if we should fork this repo and make that the canonical version. The problem is that I don't have permissions on this repo and can't add you ( or @LemonBreezes) as maintainers (which is what I would prefer). @JonWaltman is no longer active on Github. What do you think?

**Comment by minad** [comment]
> On another note, I wonder if we should fork this repo and make that the canonical version. The problem is that I don't have permissions on this repo and can't add you ( or @LemonBreezes) as maintainers (which is what I would prefer). @JonWaltman is no longer active on Github. What do you think?

I would like to help maintaining this package and I assume that this also applies to @LemonBreezes. You could either move the repository to your account or to a separate organization like emacs-orphanage. While I like the idea of the emacs-orphanage it gives the impression that packages are unmaintained. This applies also to the package gnuplot, to which I recently contributed and which is maintained (cc @tarsius, maybe this should also be moved somewhere else?). Regarding package takeover, I don't want to step on @JonWaltman's feet. In the context of the MELPA package repository there are rules about such a procedure. One should at least wait for two or more weeks after trying to contact Jon via different means (email etc). On the other hand you are already maintainer of this package as far as I understood, so maybe this matters when judging the situation. Let's ping @tarsius as MELPA maintainer for advice.

**Comment by tarsius** [comment]
In part due to recent feedback from Steve and Donald I am trying to refocus the orphanage on its original purpose: provide a place where maintainers can drop of their packages so they don't have to be involved in the process of finding a new maintainer. It turned out that proposing the use of the orphanage when others already volunteered to take over a package has the potential to causes more issues than it solves.

Even if that weren't the case I think it is always preferable to create a dedicated organization if the original maintainer wants to step back or has already done so. Finding a new home is also the goal for packages that are already in the orphanage be that a new organization or the user account of a new maintainer. Since the plan here is to have multiple maintainers I recommend using a dedicated organization.

**Comment by minad** [comment]
@tarsius Thank you! @CeleritasCelery Does it sound acceptable to you to create a separate organization for this package?

**Comment by tarsius** [comment]
Just keep in mind that it is necessary to be a member to be able to transfer to an organization, so the old maintainer would either have to temporarily (or if they desire permanently) join the organization, or they would have to transfer to a user account of a member and that person would then forward the repository to the organization.

**Comment by minad** [comment]
@JonWaltman Thank you for adding me and of course thank you for this exceptional package! There is no need to move this package as long as there are enough maintainers around with access here.

**Comment by JonWaltman** [comment]
Hey all, this is the original creator and repository owner. I'm happy you all are still interested in the package and I apologize for no longer being active. 

I am happy to transfer ownership to whoever wants to assume it, add members, permissions, or anything else that you want to do. 

Just let me know how you want to proceed and I'll do as needed.

Thanks for all the interest and good luck!

**Comment by minad** [comment]
@JonWaltman The question is if you are happy to add new maintainers from time to time or get involved with such basic administratory tasks in the future. If yes, transferring the repository is not really beneficial. If you don't want to be involved in these further steps a transfer to an organization would be the best approach. The organization could start for example with you and @CeleritasCelery as initial members with administrator rights. There is no need to hurry with that decision.
